scrape_configs:
  - job_name: 'deku'
    scrape_interval: 100ms
    static_configs:
      # TODO: currently these are hard-coded for development/local benchmarking
      # But we might want to do this more dynamically. Maybe Prometheus has some
      # dynamic config?
      - targets: ['localhost:9000', 'localhost:9001', 'localhost:9002']
