[build]
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://api.staging-ligo-ide.tez.ie/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/p/*"
  to = "/index.html"
  status = 200
  force = true