name: Hello Reason

on: [push, pull_request]

jobs:
  test:
    name: Tests

    strategy:
      matrix:
        system: [ubuntu, macos]

    runs-on: ${{ matrix.system }}-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install esy
        run: npm install -g @esy-nightly/esy

      - uses: esy/github-action@master
        with:
          cache-key: ${{ matrix.system }}-${{ hashFiles('esy.lock/index.json') }}

      - name: Run Code formatter
        run: esy b dune build @fmt
      
      - name: Run Check
        run: esy b dune build @check

      - name: Run tests
        run: esy test
